### ISSUE TITLE
Chart type "outlabeledPie" is not supported

### ISSUE THREAD

**Issue by hzh0292** [typpo/quickchart-python#10]
The example of outlabeledPie can't get the expected output image.
[The expected output image.](https://quickchart.io/chart?c=%7B%0A%20%20%22type%22%3A%20%22outlabeledPie%22%2C%0A%20%20%22data%22%3A%20%7B%0A%20%20%20%20%22labels%22%3A%20%5B%22ONE%22%2C%20%22TWO%22%2C%20%22THREE%22%2C%20%22FOUR%22%2C%20%22FIVE%22%5D%2C%0A%20%20%20%20%22datasets%22%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20%22backgroundColor%22%3A%20%5B%22%23FF3784%22%2C%20%22%2336A2EB%22%2C%20%22%234BC0C0%22%2C%20%22%23F77825%22%2C%20%22%239966FF%22%5D%2C%0A%20%20%20%20%20%20%20%20%22data%22%3A%20%5B1%2C%202%2C%203%2C%204%2C%205%5D%0A%20%20%20%20%7D%5D%0A%20%20%7D%2C%0A%20%20%22options%22%3A%20%7B%0A%20%20%20%20%22plugins%22%3A%20%7B%0A%20%20%20%20%20%20%22legend%22%3A%20false%2C%0A%20%20%20%20%20%20%22outlabels%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22text%22%3A%20%22%25l%20%25p%22%2C%0A%20%20%20%20%20%20%20%20%22color%22%3A%20%22white%22%2C%0A%20%20%20%20%20%20%20%20%22stretch%22%3A%2035%2C%0A%20%20%20%20%20%20%20%20%22font%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22resizable%22%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%22minSize%22%3A%2012%2C%0A%20%20%20%20%20%20%20%20%20%20%22maxSize%22%3A%2018%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)
[Output image with python sdk.](https://quickchart.io/chart?c=%7B%0A++%22type%22%3A+%22outlabeledPie%22%2C%0A++%22data%22%3A+%7B%0A++++%22labels%22%3A+%5B%22ONE%22%2C+%22TWO%22%2C+%22THREE%22%2C+%22FOUR%22%2C+%22FIVE%22%5D%2C%0A++++%22datasets%22%3A+%5B%7B%0A++++++++%22backgroundColor%22%3A+%5B%22%23FF3784%22%2C+%22%2336A2EB%22%2C+%22%234BC0C0%22%2C+%22%23F77825%22%2C+%22%239966FF%22%5D%2C%0A++++++++%22data%22%3A+%5B1%2C+2%2C+3%2C+4%2C+5%5D%0A++++%7D%5D%0A++%7D%2C%0A++%22options%22%3A+%7B%0A++++%22plugins%22%3A+%7B%0A++++++%22legend%22%3A+false%2C%0A++++++%22outlabels%22%3A+%7B%0A++++++++%22text%22%3A+%22%25l+%25p%22%2C%0A++++++++%22color%22%3A+%22white%22%2C%0A++++++++%22stretch%22%3A+35%2C%0A++++++++%22font%22%3A+%7B%0A++++++++++%22resizable%22%3A+true%2C%0A++++++++++%22minSize%22%3A+12%2C%0A++++++++++%22maxSize%22%3A+18%0A++++++++%7D%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D&w=500&h=300&bkg=%23ffffff&devicePixelRatio=1.0&f=png&v=2.9.4)

**Comment by typpo** [comment]
This is a side effect of the outlabeledPie plugin.  It is sensitive to canvas size and resolution.  If there is not enough room for the labels, it won't be able to render them.

If you set `devicePixelRatio` to 2 in your Python example, for example, the labels will show.
