### ISSUE TITLE
JSONDecodeError on get_short_url

### ISSUE THREAD

**Issue by ClawdI** [typpo/quickchart-python#2]
https://github.com/typpo/quickchart-python/blob/74af83d8c0ac90b014eb3699caba044bad128a54/quickchart/__init__.py#L55
Shouldn't the link be the variable "path" on this line? It fixes my issues since I just want to get the short URL and it's pulling an image file and it crashes on the line 62 when parsing the data.

**Comment by typpo** [comment]
Thank you for catching this - I've changed that line and published the fixed package.
