### ISSUE TITLE
Wrong variable name on get_bytes

### ISSUE THREAD

**Issue by ClaudioPinho** [typpo/quickchart-python#3]
https://github.com/typpo/quickchart-python/blob/12b1cec3082cd1877d1d76e7d9da68f995f3600e/quickchart/__init__.py#L69
Should be "resp" instead of "response", "response" never gets defined

**Comment by typpo** [comment]
Thanks again.  Fixed this and added a test.  

These issues were the result of a recent refactor.  I will have to properly mock `get_short_url` and expand test coverage there too.

**Comment by ClaudioPinho** [comment]
No problem, I am glad I could help
