### ISSUE TITLE
getGradientFill not working

### ISSUE THREAD

**Issue by cmabastar** [typpo/quickchart-python#4]
Hi, 

Is there a way to make getGradientFillHelper work? It seems to be a function call on quickcharts but we only do strings in the dict

```python
"datasets": [
    {
        "fill": True,
        "pointRadius": 0,
        "borderColor": ["rgba(54, 162, 235, 1)"],
        "backgroundColor": 'getGradientFillHelper(\'vertical\', ["rgba(63, 100, 249, 0.2)", "rgba(255, 255, 255, 0.2)"])',
        "borderWidth": 1.2,
        "hidden": False,
        "data": timeseries,
        "keyword": keyword,
    }
],
```

**Comment by typpo** [comment]
Hi cmabastar,

You'll have to supply the entire chart definition as a string, like in this example: https://github.com/typpo/quickchart-python/blob/master/examples/simple_example_with_function.py

If you want to keep the dict-based approach, another option is to add a placeholder string for `backgroundColor`, use `json.dumps` to convert the object to json, and then find and replace the value of `backgroundColor`.

**Comment by cmabastar** [comment]
Thanks @typpo , Did the find and replace method since i was doing a dict approach.

**Comment by typpo** [comment]
FYI, I've added a more elegant way to handle JS functions in Python as of release 0.2.0.  You can now import `QuickChartFunction` to include JS.

For example:
```py
from quickchart import QuickChart, QuickChartFunction

qc = QuickChart()
qc.config = {
    "type": "bar",
    "data": {
        "labels": ["Hello world", "Test"],
        "datasets": [{
            "label": "Foo",
            "data": [1, 2],
            "backgroundColor": QuickChartFunction("getGradientFillHelper('vertical', ['rgba(63, 100, 249, 0.2)', 'rgba(255, 255, 255, 0.2)'])"),
        }]
    }
}
```
